//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace IGFixer.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class Attributes {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attributes", typeof(AttributeObject))]
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyProperty", typeof(PropertyProperty))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class AttributeObject {
        
        private string valueField;
        
        private BoundingBox positionField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class BoundingBox {
        
        private string beginField;
        
        private string lengthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Begin {
            get {
                return this.beginField;
            }
            set {
                this.beginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class ConstitutiveStatementOfFact {
        
        private BoundingBox positionField;
        
        private ConstitutedEntity constitutedEntityField;
        
        private ConstitutiveFunctionObject constitutiveFunctionField;
        
        private Properties constitutingPropertiesField;
        
        private ActivationCondition activationConditionField;
        
        private ExecutionConstraint executionConstraintField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public ConstitutedEntity ConstitutedEntity {
            get {
                return this.constitutedEntityField;
            }
            set {
                this.constitutedEntityField = value;
            }
        }
        
        /// <remarks/>
        public ConstitutiveFunctionObject ConstitutiveFunction {
            get {
                return this.constitutiveFunctionField;
            }
            set {
                this.constitutiveFunctionField = value;
            }
        }
        
        /// <remarks/>
        public Properties ConstitutingProperties {
            get {
                return this.constitutingPropertiesField;
            }
            set {
                this.constitutingPropertiesField = value;
            }
        }
        
        /// <remarks/>
        public ActivationCondition ActivationCondition {
            get {
                return this.activationConditionField;
            }
            set {
                this.activationConditionField = value;
            }
        }
        
        /// <remarks/>
        public ExecutionConstraint ExecutionConstraint {
            get {
                return this.executionConstraintField;
            }
            set {
                this.executionConstraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class ConstitutedEntity {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConstitutedEntity", typeof(ConstitutedEntityObject))]
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyProperty", typeof(PropertyProperty))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class ConstitutedEntityObject {
        
        private string valueField;
        
        private BoundingBox positionField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class InstitutionalExpression {
        
        private BoundingBox positionField;
        
        private object itemField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstitutionalStatement", typeof(InstitutionalStatement))]
        [System.Xml.Serialization.XmlElementAttribute("StatementOfFact", typeof(StatementOfFact))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute("OrElse", Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class InstitutionalStatement {
        
        private BoundingBox positionField;
        
        private bool inversionField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public bool Inversion {
            get {
                return this.inversionField;
            }
            set {
                this.inversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConstitutiveStatement", typeof(ConstitutiveInstitutionalStatement))]
        [System.Xml.Serialization.XmlElementAttribute("InstitutionalStatementCombination", typeof(InstitutionalStatementCombination))]
        [System.Xml.Serialization.XmlElementAttribute("OrElse", typeof(InstitutionalStatement))]
        [System.Xml.Serialization.XmlElementAttribute("RegulativeStatement", typeof(RegulativeInstitutionalStatement))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class ConstitutiveInstitutionalStatement {
        
        private BoundingBox positionField;
        
        private ConstitutedEntity constitutedEntityField;
        
        private DeonticObject deonticField;
        
        private ConstitutiveFunctionObject constitutiveFunctionField;
        
        private Properties constitutingPropertiesField;
        
        private ActivationCondition activationConditionField;
        
        private ExecutionConstraint executionConstraintField;
        
        private InstitutionalStatement orElseField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public ConstitutedEntity ConstitutedEntity {
            get {
                return this.constitutedEntityField;
            }
            set {
                this.constitutedEntityField = value;
            }
        }
        
        /// <remarks/>
        public DeonticObject Deontic {
            get {
                return this.deonticField;
            }
            set {
                this.deonticField = value;
            }
        }
        
        /// <remarks/>
        public ConstitutiveFunctionObject ConstitutiveFunction {
            get {
                return this.constitutiveFunctionField;
            }
            set {
                this.constitutiveFunctionField = value;
            }
        }
        
        /// <remarks/>
        public Properties ConstitutingProperties {
            get {
                return this.constitutingPropertiesField;
            }
            set {
                this.constitutingPropertiesField = value;
            }
        }
        
        /// <remarks/>
        public ActivationCondition ActivationCondition {
            get {
                return this.activationConditionField;
            }
            set {
                this.activationConditionField = value;
            }
        }
        
        /// <remarks/>
        public ExecutionConstraint ExecutionConstraint {
            get {
                return this.executionConstraintField;
            }
            set {
                this.executionConstraintField = value;
            }
        }
        
        /// <remarks/>
        public InstitutionalStatement OrElse {
            get {
                return this.orElseField;
            }
            set {
                this.orElseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute("Deontic", Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class DeonticObject {
        
        private string valueField;
        
        private BoundingBox positionField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute("ConstitutiveFunction", Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class ConstitutiveFunctionObject {
        
        private string valueField;
        
        private BoundingBox positionField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute("ConstitutingProperties", Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class Properties {
        
        private BoundingBox positionField;
        
        private object[] itemsField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyProperty", typeof(PropertyProperty))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class PropertyProperty {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        [System.Xml.Serialization.XmlElementAttribute("NestedProperty", typeof(Properties))]
        [System.Xml.Serialization.XmlElementAttribute("Property", typeof(Properties))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        NestedInstitutionalExpression,
        
        /// <remarks/>
        NestedProperty,
        
        /// <remarks/>
        Property,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class ActivationCondition {
        
        private BoundingBox[] positionField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Position")]
        public BoundingBox[] Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivationCondition", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class ExecutionConstraint {
        
        private BoundingBox[] positionField;
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Position")]
        public BoundingBox[] Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExecutionConstraint", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class InstitutionalStatementCombination {
        
        private BoundingBox positionField;
        
        private InstitutionalStatement leftInstitutionalStatementField;
        
        private LogicalOperator logicalOperatorField;
        
        private InstitutionalStatement rightInstitutionalStatementField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public InstitutionalStatement LeftInstitutionalStatement {
            get {
                return this.leftInstitutionalStatementField;
            }
            set {
                this.leftInstitutionalStatementField = value;
            }
        }
        
        /// <remarks/>
        public LogicalOperator LogicalOperator {
            get {
                return this.logicalOperatorField;
            }
            set {
                this.logicalOperatorField = value;
            }
        }
        
        /// <remarks/>
        public InstitutionalStatement RightInstitutionalStatement {
            get {
                return this.rightInstitutionalStatementField;
            }
            set {
                this.rightInstitutionalStatementField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class LogicalOperator {
        
        private BoundingBox positionField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AND", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("OR", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("XOR", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        XOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class RegulativeInstitutionalStatement {
        
        private BoundingBox positionField;
        
        private Attributes attributesField;
        
        private Object objectField;
        
        private DeonticObject deonticField;
        
        private AimObject aimField;
        
        private ActivationCondition activationConditionField;
        
        private ExecutionConstraint executionConstraintField;
        
        private InstitutionalStatement orElseField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public Attributes Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public Object Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        public DeonticObject Deontic {
            get {
                return this.deonticField;
            }
            set {
                this.deonticField = value;
            }
        }
        
        /// <remarks/>
        public AimObject Aim {
            get {
                return this.aimField;
            }
            set {
                this.aimField = value;
            }
        }
        
        /// <remarks/>
        public ActivationCondition ActivationCondition {
            get {
                return this.activationConditionField;
            }
            set {
                this.activationConditionField = value;
            }
        }
        
        /// <remarks/>
        public ExecutionConstraint ExecutionConstraint {
            get {
                return this.executionConstraintField;
            }
            set {
                this.executionConstraintField = value;
            }
        }
        
        /// <remarks/>
        public InstitutionalStatement OrElse {
            get {
                return this.orElseField;
            }
            set {
                this.orElseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class Object {
        
        private NestedObject directObjectField;
        
        private NestedObject indirectObjectField;
        
        /// <remarks/>
        public NestedObject DirectObject {
            get {
                return this.directObjectField;
            }
            set {
                this.directObjectField = value;
            }
        }
        
        /// <remarks/>
        public NestedObject IndirectObject {
            get {
                return this.indirectObjectField;
            }
            set {
                this.indirectObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class NestedObject {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NestedInstitutionalExpression", typeof(InstitutionalExpression))]
        [System.Xml.Serialization.XmlElementAttribute("Object", typeof(ObjectObject))]
        [System.Xml.Serialization.XmlElementAttribute("PropertyProperty", typeof(PropertyProperty))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class ObjectObject {
        
        private string valueField;
        
        private BoundingBox positionField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute("Aim", Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class AimObject {
        
        private string valueField;
        
        private BoundingBox positionField;
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class StatementOfFact {
        
        private BoundingBox positionField;
        
        private bool inversionField;
        
        private object itemField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public bool Inversion {
            get {
                return this.inversionField;
            }
            set {
                this.inversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Combination", typeof(InstitutionalStatementCombination))]
        [System.Xml.Serialization.XmlElementAttribute("ConstitutiveStatementOfFact", typeof(ConstitutiveStatementOfFact))]
        [System.Xml.Serialization.XmlElementAttribute("RegulativeStatementOfFact", typeof(RegulativeStatementOfFact))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    public partial class RegulativeStatementOfFact {
        
        private BoundingBox positionField;
        
        private Attributes attributesField;
        
        private Object objectField;
        
        private AimObject aimField;
        
        private ActivationCondition activationConditionField;
        
        private ExecutionConstraint executionConstraintField;
        
        /// <remarks/>
        public BoundingBox Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        public Attributes Attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        public Object Object {
            get {
                return this.objectField;
            }
            set {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        public AimObject Aim {
            get {
                return this.aimField;
            }
            set {
                this.aimField = value;
            }
        }
        
        /// <remarks/>
        public ActivationCondition ActivationCondition {
            get {
                return this.activationConditionField;
            }
            set {
                this.activationConditionField = value;
            }
        }
        
        /// <remarks/>
        public ExecutionConstraint ExecutionConstraint {
            get {
                return this.executionConstraintField;
            }
            set {
                this.executionConstraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/IG")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.example.org/IG", IsNullable=false)]
    public partial class Sentence {
        
        private string contentField;
        
        private object itemField;
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InstitutionalStatement", typeof(InstitutionalStatement))]
        [System.Xml.Serialization.XmlElementAttribute("InstitutionalStatementCombination", typeof(InstitutionalStatementCombination))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
}
